#!/usr/bin/env bash

# Is there an encrypted access token in our home?
if ! enc_access_token=$(cat ~/.gh-create-repo-access-token); then
  echo "directory does not contain a '.gh-access-token'"
  exit 1
fi

# are we currently in an initialize git repo?
if ! is_a_git_repo=$(git rev-parse --is-inside-work-tree); then
  echo "Not in a git repo, try git initing first..."
  exit 1
fi;

# do we know the correct password to decrypt our access token
if ! accessToken=$(echo -n "$enc_access_token" | openssl aes-256-cbc -d -a) ; then
    echo 'Incorrect Password'
    exit 1
fi

directoryname=${PWD##*/}
name=${2:-$directoryname}
description=${1:-" "}

data='{ "name":"'$name'", "description": "'$description'" }'
url=https://api.github.com/user/repos?access_token=$accessToken


echo "submitting... $data"

if result=$(curl "$url" -f --silent --show-error -d "$data") ; then
  remote=$(echo $result | jq -r '.ssh_url')
  echo "Setting up remote: $remote" 
  git remote add origin $remote
else
  echo 'Create repo failed'
  exit 1
fi
